remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Matrixx]
description: [A custom rom based on crDroid Android with extra pinch of salt]
relative_links:
  enabled: true
  collections: true
include:
  - Changelog.md
  - Devices.md
  - hotdog.md
  - hotdogb.md
  - lemonade.md
  - lemonadep.md      
  - README.md
